# Generated by Django 5.0.7 on 2024-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
