# Generated by Django 5.0.7 on 2024-09-19 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Representative', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('user', models.OneToOneField(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('companies', models.ManyToManyField(related_name='companies_set', to='Representative.company')),
            ],
        ),
    ]
