# Generated by Django 5.0.7 on 2024-08-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="deal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.deal"
            ),
        ),
    ]
