# Generated by Django 5.0.7 on 2024-09-19 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Representative', '0002_initial'),
        ('Service', '0001_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchGroup',
            fields=[
                ('group', models.OneToOneField(db_column='group_name', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='User.group')),
                ('max_members', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('user', models.OneToOneField(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('max_enrolled_branches', models.PositiveSmallIntegerField(default=1)),
                ('branches', models.ManyToManyField(related_name='salesmen_set', to='Salesman.branchgroup')),
            ],
            options={
                'verbose_name_plural': 'Salesmen',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_state', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(0, 'Interested'), (1, 'First Meeting'), (2, 'Further Motivation'), (100, 'Acquired'), (-1, 'Lost')], default=0)),
                ('attributed_to', models.ForeignKey(db_column='branch_name', on_delete=django.db.models.deletion.CASCADE, to='Salesman.branchgroup')),
                ('representing', models.ForeignKey(db_column='company_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='Representative.company')),
                ('service', models.ForeignKey(db_column='service_name', on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
                ('service_seeker', models.ForeignKey(db_column='seeker_email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salesman', models.ForeignKey(db_column='salesman_email', on_delete=django.db.models.deletion.CASCADE, to='Salesman.salesman')),
            ],
            options={
                'ordering': ['-time_of_state'],
            },
        ),
    ]
