# Generated by Django 5.0.7 on 2024-09-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('google_meet_url', models.URLField()),
                ('deal_id', models.OneToOneField(db_column='deal_id', on_delete=django.db.models.deletion.CASCADE, to='Salesman.deal')),
            ],
        ),
    ]
