# Generated by Django 5.0.7 on 2024-09-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0002_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='google_meet_url',
            field=models.URLField(unique=True),
        ),
    ]
