# Generated by Django 5.0.7 on 2024-09-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesman', '0003_alter_meeting_google_meet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='deal_id',
            field=models.OneToOneField(db_column='deal_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Salesman.deal'),
        ),
    ]
