# Generated by Django 5.0.7 on 2024-09-19 23:12

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='name')),
                ('permissions', models.ManyToManyField(related_name='custom_group_set', to='auth.permission', verbose_name='permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(max_length=40)),
                ('groups', models.ManyToManyField(to='User.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('quit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Salesman', 'Salesman'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Client', 'Client'), ('Representative', 'Representative')], max_length=40)),
                ('belonging_to', models.ForeignKey(db_column='belonging_to_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonging_to_set', to='User.group')),
                ('responsible_for', models.ForeignKey(db_column='responsible_for_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_for_set', to='User.group')),
                ('user', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
    ]
