# Generated by Django 5.0.7 on 2024-08-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='companies',
            field=models.ManyToManyField(related_name='companies_set', to='user.company'),
        ),
    ]
