# Generated by Django 5.0.7 on 2024-08-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_representative_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_state',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
