# Generated by Django 5.0.7 on 2024-09-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_deal_date_of_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='belonging_to',
            field=models.ForeignKey(db_column='belonging_to_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonging_to_set', to='user.group'),
        ),
    ]
