# Generated by Django 5.0.7 on 2024-09-03 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userhistory_belonging_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='service_seeker',
            field=models.ForeignKey(db_column='seeker_email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
