# Generated by Django 5.0.7 on 2024-09-16 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_deal_service_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_state',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
