# Generated by Django 5.0.7 on 2024-09-16 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_deal_date_of_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_state',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
