# Generated by Django 5.0.7 on 2024-09-18 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_deal_date_of_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_state',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
