# Generated by Django 5.0.7 on 2024-10-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskUpgrade',
            fields=[
                ('client', models.OneToOneField(db_column='client_email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Client.client')),
                ('manager', models.ForeignKey(db_column='manager_email', on_delete=django.db.models.deletion.CASCADE, to='Manager.manager')),
            ],
        ),
    ]
